title: Broseley Camera Club
email: BroseleyPhotography@gmail.com
description: A simple site for a local club.
twitter_username: @BroseleyPhoto

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  programme:
    output: true
    permalink: /programme/:path/


